apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-custom-gw
spec:
  hosts:
  - "webapp.istioinaction.io"
  gateways:
  - custom-coolstore-gateway
  http:
  - route:
    - destination:
        host: webapp
        port:
          number: 8080