---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forum
    version: v1
  name: forum
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: forum
      version: v1
  template:
    metadata:
      labels:
        app: forum
        version: v1
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: istioinaction/forum:latest
        imagePullPolicy: IfNotPresent
        name: forum
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
