apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: statsd
  name: statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      run: statsd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: statsd
    spec:
      containers:
      - image: nanit/statsd-daemon:ead3be4
        imagePullPolicy: IfNotPresent
        name: statsd
        ports:
        - containerPort: 8125
          protocol: UDP
        - containerPort: 8126
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30