helm template install/kubernetes/helm/istio \
  --name istio \
  --namespace istio-system \
  --set gateways.enabled=true \
  --set security.enabled=false \
  --set global.mtls.enabled=false \
  --set galley.enabled=false \
  --set global.useMCP=false \
  --set sidecarInjectorWebhook.enabled=false \
  --set mixer.enabled=false \
  --set mixer.policy.enabled=false \
  --set mixer.telemetry.enabled=false \
  --set prometheus.enabled=false \
  --set grafana.enabled=false \
  --set tracing.enabled=false \
  --set kiali.enabled=false \
  --set pilot.sidecar=false  > istio-minimal.yaml